import type { CaseRecord } from "@/types/mockdata/cases";

export const caseRecords: CaseRecord[] = [
  {
    id: "case-9284",
    number: "#9284",
    title: "Harassment Report",
    category: "Direct Threat",
    severity: "High",
    status: "Assigned",
    decision: null,
    openedAt: "Opened 12m ago",
    assignedToMe: true,
    wasAssignedToMe: true,
    needsVote: true,
    harmfulScore: 0.92,
    aiReason: "Toxic language with implied doxxing threat",
    offender: "User_VoidWalker",
    reporter: "BruhGunned",
    flaggedMessage:
      "You are absolute garbage at this game, why don't you just leave before I find where you live and show you some real skill.",
    summary:
      "Flagged from general chat after a heated argument escalated into threatening language. Context suggests the offender repeated the same threat after being warned by others in the room.",
    voteBreakdown: "6 punish • 1 dismiss",
    outcome:
      "Case is still active. Current consensus leans strongly toward punishment, but quorum has not been fully reached yet.",
    chainRef: "0X82...F2E1",
  },
  {
    id: "case-9281",
    number: "#9281",
    title: "Trash-talk Dispute",
    category: "Escalated Banter",
    severity: "Low",
    status: "Voting",
    decision: null,
    openedAt: "Opened 45m ago",
    assignedToMe: false,
    wasAssignedToMe: false,
    needsVote: false,
    harmfulScore: 0.39,
    aiReason: "Manual flag after repeated taunts in a match thread",
    offender: "GamerPro_99",
    reporter: "Ashwin",
    flaggedMessage:
      "LMAO get wrecked kid, literally zero skill detected in your gameplay profile.",
    summary:
      "Community members flagged the message during an argument about ranked play. The language is rude but the room is split on whether it crosses the threshold for punishment.",
    voteBreakdown: "2 punish • 3 dismiss",
    outcome:
      "Still in voting. Current sentiment suggests dismissal unless new context shows targeted harassment.",
    chainRef: "0X42...A911",
  },
  {
    id: "case-9270",
    number: "#9270",
    title: "Hate-speech Review",
    category: "Protected Group Abuse",
    severity: "High",
    status: "Resolved",
    decision: "Punished",
    openedAt: "Opened 2h ago",
    resolvedAt: "Resolved 94m ago",
    assignedToMe: false,
    wasAssignedToMe: true,
    needsVote: false,
    harmfulScore: 0.88,
    aiReason: "Severe hateful-conduct indicators against a protected group",
    offender: "C_D0_99",
    reporter: "Arnav",
    flaggedMessage:
      "People like you should not even be allowed in this server.",
    summary:
      "Escalated after multiple users reported slur-adjacent language and repeated hostile replies aimed at a protected group in a public thread.",
    voteBreakdown: "7 punish • 1 dismiss",
    outcome:
      "Case resolved with punishment after jurors reviewed the original message and follow-up replies. The decision remains visible for transparency review.",
    chainRef: "0X91...DD42",
  },
  {
    id: "case-9264",
    number: "#9264",
    title: "Self-harm Encouragement",
    category: "Critical Harm",
    severity: "High",
    status: "Assigned",
    decision: null,
    openedAt: "Opened 4m ago",
    assignedToMe: true,
    wasAssignedToMe: true,
    needsVote: true,
    harmfulScore: 0.98,
    aiReason: "Direct self-harm encouragement with explicit second-person targeting",
    offender: "hexdown",
    reporter: "Shreyan",
    flaggedMessage:
      "If you are that mad over a game, just go kill yourself already.",
    summary:
      "Emergency case created from a direct reply in general chat. The language is explicit, targeted, and aligned with the highest-risk moderation category.",
    voteBreakdown: "1 punish • 0 dismiss",
    outcome:
      "Case has just entered jury review. This one requires immediate attention because the language is unambiguous.",
    chainRef: "0X77...C108",
  },
  {
    id: "case-9258",
    number: "#9258",
    title: "Spam Flag Review",
    category: "Repeated Posting",
    severity: "Medium",
    status: "Resolved",
    decision: "Dismissed",
    openedAt: "Opened 7h ago",
    resolvedAt: "Resolved 6h ago",
    assignedToMe: false,
    wasAssignedToMe: true,
    needsVote: false,
    harmfulScore: 0.27,
    aiReason: "Repeated posting pattern but no abusive content",
    offender: "NovaPulse",
    reporter: "BruhGunned",
    flaggedMessage:
      "join my lobby join my lobby join my lobby join my lobby",
    summary:
      "Reported for spam during peak hours. Review concluded the behavior was disruptive but did not warrant punishment under current room rules.",
    voteBreakdown: "1 punish • 5 dismiss",
    outcome:
      "Resolved with dismissal and no account penalty. Message stayed visible but moderators noted the pattern for future spam escalation.",
    chainRef: "0X11...B812",
  },
];
